config/routes.rb
Csl::Application.routes.draw do
  get "fame4good/home"

  get "fame4good/search"

  get "fame4good/campaign"

  get "fame4good/howitworks"

  get "fame4good/aboutus"

  get "fame4good/donation"

  get "fame4good/profile"

  get "fame4good/register"

  get "fame4good/confirmation"

  get "fame4good/payment"

  get 'mnm' => 'malaria#home'

  root :to => 'pages#home'

  get 'symmetry_partners' => 'symmetry_partners#sp'

  get 'sp-advisor' => 'symmetry_partners#sp-advisor'

  get 'sp-client' => 'symmetry_partners#sp-client'

  get 'sp-learnmore' => 'symmetry_partners#sp-learnmore'

  get 'knightpoint' => 'knight_point#home'

  get 'knightpoint-careers' => 'knight_point#careers'

  get 'knightpoint-about' => 'knight_point#about'

  get 'knightpoint-contracts' => 'knight_point#contracts'

  get 'knightpoint-expertise' => 'knight_point#expertise'

  get 'knightpoint-sectors' => 'knight_point#sectors'

  get 'knightpoint-media' => 'knight_point#media'

  get 'dashboard' => 'donor_portfolio#dashboard'

  get 'blank' => 'donor_portfolio#blank'

  get 'ppmdsearch' => 'donor_portfolio#search'

  get 'history' => 'donor_portfolio#history'

  get 'faq' => 'donor_portfolio#faqs'

  get 'project' => 'donor_portfolio#projectpage'

  get 'account' => 'donor_portfolio#account'

  get 'contact' => 'donor_portfolio#contact'

  get 'funds' => 'donor_portfolio#browsefunds'

  get 'reports' => 'donor_portfolio#reports'  

  get 'donation' => 'donor_portfolio#donation'

  get 'allocation' => 'donor_portfolio#allocation'

  get 'project-complete' => 'donor_portfolio#project_complete'

  get 'login' => 'donor_portfolio#login'

  get 'admin' => 'donor_portfolio#admin'

  get 'manageusers' => 'donor_portfolio#manageusers'

  get 'mul' => 'donor_portfolio#mul'

  get 'addfunds' => 'donor_portfolio#add_funds'

  get 'complete-projects' => 'donor_portfolio#complete-projects'

  get 'malaria' => 'pages#malarianomore'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/donor_portfolio_controller.rb
class DonorPortfolioController < ApplicationController
  def dashboard
  end

  def allocate
  end

  def blank
  end

  def multipleall
  end

end

app/controllers/downto_basics_controller.rb
class DowntoBasicsController < ApplicationController
  def dtb
  end

  def dtbsearch
  end

  def dtbhome
  end
end

app/controllers/fame4good_controller.rb
class Fame4goodController < ApplicationController
  def home
  end

  def search
  end

  def campaign
  end

  def howitworks
  end

  def aboutus
  end

  def donation
  end

  def profile
  end

  def register
  end

  def payment
  end  

  def confirmation
  end  

end

app/controllers/holiday_app_controller.rb
class HolidayAppController < ApplicationController
  def home
  end
end

app/controllers/knight_point_controller.rb
class KnightPointController < ApplicationController
  def home
  end
end

app/controllers/malaria_controller.rb
class MalariaController < ApplicationController
  def MalariaNoMore
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
  end

  def blank
  end
end

app/controllers/symmetry_partners_controller.rb
class SymmetryPartnersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fame4good_helper.rb
module Fame4goodHelper
end

app/helpers/malaria_helper.rb
module MalariaHelper
end

app/helpers/symmetry_partners_helper.rb
module SymmetryPartnersHelper
end

app/views/donor_portfolio/add_funds.html.erb
<%= render 'layouts/header' %>

<div class="row">
	<div class="col-sm-12">

<h2>Add Funds</h2>
<a href="#" class="btn btn-primary">Add Funds</a>
	</div>
</div>



<%= render 'layouts/footer' %>

app/views/donor_portfolio/contact.html.erb
<%= render 'layouts/header' %>

<script type="text/javascript" language="javascript">
function step2() {
        document.getElementById('step1_container').style.display = 'none';
        document.getElementById('step2_container').style.display = 'block';
}
</script>
					<div class="row">					
						<div class="col-sm-12" id="step1_container">
							<!-- start: TEXT FIELDS PANEL -->
							<div class="panel panel-default"  >
								<div class="panel-body">
									<form role="form" class="form-horizontal">
										<div class="form-group">
											<label class="col-sm-2 control-label" for="form-field-1">
												Member to Contact
											</label>
											<div class="col-sm-9">
												<label class="radio-inline">
													<input type="radio" value="" name="optionsRadios" class="grey">
													Site Administrator
												</label>
												<label class="radio-inline">
													<input type="radio" value="" name="optionsRadios" class="grey">
													Research Director
												</label>
											</div>
										</div>
										<div class="form-group">
											<label class="col-sm-2 control-label" for="form-field-1">
												Subject
											</label>
											<div class="col-sm-9">
												<input type="text" id="form-field-1" class="form-control">
											</div>
										</div>
										<div class="form-group">
											<label class="col-sm-2 control-label" for="form-field-1">
												Contact Number
											</label>
											<div class="col-sm-9">
												<input type="text" p id="form-field-1" class="form-control">
											</div>
										</div>
										<div class="form-group">
											<label class="col-sm-2 control-label" for="form-field-1">
												Message
											</label>
											<div class="col-sm-9">
												<textarea id="form-field-22" class="form-control" rows="8"></textarea>
											</div>
										</div>
										<div class="form-group">
											<label class="col-sm-2 control-label" for="form-field-1">
											
											</label>
											<div class="col-sm-9">
												<label class="radio-inline">
													<input type="checkbox" value="" name="optionsRadios" class="grey">
													Send a copy of this email to me.
												</label>
											</div>
										</div>
										<div class="form-group">
											<label class="col-sm-2 control-label" for="form-field-1">
											</label>
											<div class="col-sm-9">
										<div class="col-sm-8">
										<input class="btn btn-success" type="button" onclick="javascript:step2();" value="Submit"/>

										<a class="btn btn-red" href="#">
											Cancel</a>
											</label>
											</div>
									</div>
									</form>
								</div>
							</div>
							<!-- end: TEXT FIELDS PANEL -->
						</div>
					</div>

					<div class="row">					
					<div class="alert alert-block alert-success col-sm-8" id="step2_container" style="display:none; margin-left:100px;">
										<button data-dismiss="alert" class="close" type="button">
											×
										</button>
										<h4 class="alert-heading"><i class="icon-ok-sign"></i> Success!</h4>
										<p>
											Your message has been sent to our team. We will be in touch soon!
										</p>
										<p>
											<a href="dashboard.html" class="btn btn-green">
												Go Back to My Portfolio
											</a>

										</p>
									</div>
					</div>

<%= render 'layouts/footer' %>

app/views/donor_portfolio/dashboard.html.erb
<%= render 'layouts/header' %>
					<div class="row">
						<div class="col-sm-4">
							<div class="core-box">
								<div class="heading">
									<a href="ppmdsearch.html"><i class="clip-location circle-icon circle-green"></i>
									<h2>Browse Projects</h2></a>
								</div>
								<div class="content">
									Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
								</div>
								<a class="view-more" href="ppmdsearch.html">
									View More <i class="clip-arrow-right-2"></i>
								</a>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="core-box">
								<div class="heading">
									<a href="account"><i class="clip-cog-2 circle-icon circle-teal"></i>
									<h2>Manage Account</h2></a>
								</div>
								<div class="content">
									Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
								</div>
								<a class="view-more" href="funds.html">
									View More <i class="clip-arrow-right-2"></i>
								</a>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="core-box">
								<div class="heading">
									<a href="history"><i class="clip-bars circle-icon circle-bricky"></i>
									<h2>View Transaction History</h2></a>
								</div>
								<div class="content">
									Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
								</div>
								<a class="view-more" href="history">
									View More <i class="clip-arrow-right-2"></i>
								</a>
							</div>
						</div>

					</div>
<div class="row">
						<div class="col-md-12">
							<!-- start: BASIC TABLE PANEL -->
							<div class="panel panel-default">
								<div class="panel-heading">
									<i class="icon-external-link-sign"></i>
									Portfolio Overview

								</div>
								<div class="panel-body">
									<table class="table table-hover" id="sample-table-1">
										<thead>
											<tr>
												<th class="center">Unallocated</th>
												<th class="center">Allocated to Active Projects</th>
												<th class="center">Allocated to Completed Projects</th>
												<th class="center">Total Donations</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td class="center">$12,304.00</td>
												<td class="center">$2,304.00</td>
												<td class="center">$304.00</td>
												<td class="center">$16,304.00</td>
											</tr>

										</tbody>
									</table>
								</div>
							</div>
							<!-- end: BASIC TABLE PANEL -->
						</div>
</div>
<div class="row">
						<div class="col-md-6">
							<!-- start: BASIC CHART PANEL -->
							<div class="panel panel-default">
								<div class="panel-heading">
									<i class="icon-external-link-sign"></i>
									My Allocations

								</div>
<div class="col-sm-12">
											<div class="tabbable">
												<ul id="myTab4" class="nav nav-tabs tab-padding tab-space-3 tab-blue">
													<li class="active">
														<a href="#panel_tab3_example1" data-toggle="tab">
															Total Donations
														</a>
													</li>
													<li>
														<a href="#panel_tab3_example2" data-toggle="tab">
															Category
														</a>
													</li>
													<!--<li>
														<a href="#panel_tab3_example3" data-toggle="tab">
															Status
														</a>
													</li>-->
												</ul>
												<div class="tab-content">
													<div class="tab-pane in active" id="panel_tab3_example1">
															<img src="assets/image.png" width="100%">
													</div>
													<div class="tab-pane" id="panel_tab3_example2">
															<img src="assets/category.png" width="70%">
													</div>
													<div class="tab-pane" id="panel_tab3_example3">
														<img src="assets/image.png" width="100%">
													</div>
												</div>
											</div>
										</div>
				
							
	
							</div>
							<!-- end: BASIC CHART PANEL -->
						</div>
<div class="col-md-6">
							<!-- start: BORDERED TABLE PANEL -->
							<div class="panel panel-default">
								<div class="panel-heading">
									<i class="icon-external-link-sign"></i>
									My Resarch Projects

								</div>
								<div class="panel-body">
									<table class="table table-bordered table-hover" id="sample-table-4">
										<thead>
											<tr>
												<th>Project</th>
												<th>Category</th>
												<th>Status</th>
												<th>My Allocation</th>
												<th>% Funded</th>
												<th>Last Updated</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td><a href="project">Project 1</a></td>
												<td>Category 1</td>
												<td class="hidden-xs"><span class="label label-sm label-success">Active</span></td>
												<td>$1,000</td>
												<td>52%</td>
												<td>Sept 1, 2013</td>
											</tr>
											<tr>
												<td><a href="project">Project 1</a></td>
												<td>Category 2</td>
												<td class="hidden-xs"><span class="label label-sm label-success">Active</span></td>
												<td>$10,230</td>
												<td>25%</td>
												<td>Sept 10, 2013</td>
											</tr>
											<tr>
												<td><a href="project">Project 1</a></td>
												<td>Category 3</td>
												<td class="hidden-xs"><span class="label label-sm label-success">Active</span></td>
												<td>$11,000</td>
												<td>15%</td>
												<td>Sept 11, 2013</td>
											</tr>
											<tr>
												<td><a href="project">Project 1</a></td>
												<td>Category 4</td>
												<td class="hidden-xs"><span class="label label-sm label-success">Active</span></td>
												<td>$10,000</td>
												<td>55%</td>
												<td>Sept 12, 2013</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
							<!-- end: BORDERED TABLE PANEL -->
						</div>

					</div>


					<div class="row">

<div class="col-md-12">
	<div class="alert alert-danger" style="text-align:center;">

										<strong>PLEASE NOTE THE INFORMATION BELOW IS CONFIDENTIAL.</strong>
									</div>
							<!-- start: TIMELINE PANEL -->
							<div class="panel panel-default">
								<div class="panel-heading">
									<i class="icon-external-link-sign"></i>
									Investment Updates
								</div>
										
								<div class="panel-body">
									<div id="timeline" class="demo1">
										<div class="timeline">
											<div class="spine"></div>
											<div class="date_separator">
												<span>NOVEMBER 2013</span>
											</div>
											<ul class="columns">
												<li>
													<div class="timeline_element teal">
														<div class="timeline_title">
															<span class="timeline_label">Gene Therapy for Duchenne</span><span class="timeline_date">03 November 2013</span>
														</div>
											<div class="panel-body">
													Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec adipiscing velit, eget consectetur mas.									
												</div>

<a style="display:block;" id="readmore" onclick="myFunction();" class="btn btn-default btn-xs" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Read More...</a>

<script type="text/javascript" language="javascript">
function myFunction() {
        document.getElementById('readmore').style.display = 'none';
        document.getElementById('readless').style.display = 'block';
}

function readLess() {
        document.getElementById('readless').style.display = 'none';	
        document.getElementById('readmore').style.display = 'block';
}
</script>
<style type="text/css">

.btn-xs {
	margin-left: 20px;
	margin-right: 20px;
}

</style>
													 
											<div id="collapseOne" class="collapse" style="height: 0px;">
												<div class="panel-body">
													 lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec adipiscing velit, eget consectetur massa. Nam sed quam pellentesque, fringilla nulla at, pulvinar nisi. Quisque tincidunt ante ut rhoncus aliquam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce tempus interdum massa, tristique porta orci vestibulum fringilla. Integer tristique aliquet risus, vel sollicitudin lectus iaculis id. Donec ante felis, facilisis nec tellus quis, lobortis pretium dui. Sed eget vulputate libero, vel pellentesque urna. Maecenas vitae faucibus metus. Pellentesque feugiat viverra sem in sollicitudin. Quisque ut ornare massa. Duis quis erat aliquet, fermentum velit in, aliquet leo. Proin sagittis erat a gravida ultrices. Fusce lorem dolor, rhoncus sit amet lectus a, imperdiet consectetur mi.					
													 <a style="margin-top:10px;" onclick="readLess();"style="display:none;" id="readless" onclick="myFunction();" class="btn btn-default btn-xs" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Read Less...</a>
												</div>
											
														</div>
														<div class="readmore">
															<a href="project" class="btn btn-info">
																Go To Project Page <i class="icon-circle-arrow-right"></i>
															</a>
														</div>
													</div>
												</li>
												<li>
													<div class="timeline_element green">
														<div class="timeline_title">
															<span class="timeline_label">Another New Project</span><span class="timeline_date">11 November 2013</span>
														</div>
														<div class="content">
															<b>Lorem Ipsum</b> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's 
														</div>
														<div class="readmore">
															<a href="project" class="btn btn-info">
																Read More <i class="icon-circle-arrow-right"></i>
															</a>
														</div>
													</div>
												</li>
											</ul>
											<div class="date_separator">
												<span>DECEMBER 2013</span>
											</div>
											<ul class="columns">
												<li>
													<div class="timeline_element bricky">
														<div class="timeline_title">
															<span class="timeline_label">Another New Project</span><span class="timeline_date">08 December 2013</span>
														</div>
																<div class="content">
															<b>Lorem Ipsum</b> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's 
														</div>
														<div class="readmore">
															<a href="project" class="btn btn-info">
																Read More <i class="icon-circle-arrow-right"></i>
															</a>
														</div>
													</div>
												</li>
												<li>
													<div class="timeline_element purple">
														<div class="timeline_title">
															<span class="timeline_label">Another New Project</span><span class="timeline_date">12 December 2013</span>
														</div>
														<div class="content">
															<b>Lorem Ipsum</b> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's 
														</div>
														<div class="readmore">
															<a href="project" class="btn btn-info">
																Read More <i class="icon-circle-arrow-right"></i>
															</a>
														</div>
													</div>
												</li>
												<li>
													<div class="timeline_element">
														<div class="timeline_title">
															<span class="timeline_label">Another New Project</span><span class="timeline_date">16 December 2013</span>
														</div>
														<div class="content">
															<b>Lorem Ipsum</b> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's 
														</div>
														<div class="readmore">
															<a href="project" class="btn btn-info">
																Read More <i class="icon-circle-arrow-right"></i>
															</a>
														</div>
													</div>
												</li>
												<li>
													<div class="timeline_element teal">
														<div class="timeline_title">
															<span class="timeline_label">Another New Project</span><span class="timeline_date">18 December 2013</span>
														</div>
														<div class="content">
															<b>Lorem Ipsum</b> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's 
														</div>
														<div class="readmore">
															<a href="project" class="btn btn-info">
																Read More <i class="icon-circle-arrow-right"></i>
															</a>
														</div>
													</div>
												</li>
											</ul>
										</div>
									</div>
								</div>
							</div>
							<!-- end: TIMELINE PANEL -->

<%= render 'layouts/footer' %>

app/views/donor_portfolio/faqs.html.erb
<%= render 'layouts/header' %>
<div class="row">
						<div class="col-sm-12">
							<!-- start: ACCORDION PANEL -->
							<div class="panel panel-default">
								
								<h4 style="margin-left:20px;">Frequently Asked Questions</h4>

									
								<div class="panel-body">
									<div class="panel-group accordion-custom accordion-teal" id="accordion">
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
												<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
													<i class="icon-arrow"></i>
													What is My Donor Portfolio™?
												</a></h4>
											</div>
											<div id="collapseOne" class="panel-collapse collapse" style="height: 0px;">
												<div class="panel-body">
													My Donor Portfolio™ (MDP) is an online tool developed by PPMD to help you better visualize and manage your research donations to the organization.  You can browse projects that need funding, allocate your donation to projects of your choice, and follow the progress of those projects.  The program also allows you to name “contributing donors” whose donations to PPMD will be added to your MDP account.  The MDP summary page will allow you to see and track all of your allocations at once, in the same way that you may be used to seeing your 401K information summarized.
												</div>
											</div>
										</div>
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
												<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
													<i class="icon-arrow"></i>
													2.  What is required to set up an account?2
												</a></h4>
											</div>
											<div id="collapseTwo" class="panel-collapse collapse">
												<div class="panel-body">
													A minimum donation to PPMD of $10,000 is required to open an MDP account.  After the account is open, new donation deposits in the amount of $5000 or more can be added to the account at any time.  To  open an account simply……..
												</div>
											</div>
										</div>
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
												<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
													<i class="icon-arrow"></i>
													3.  How do I let PPMD know that an incoming check should be deposited into my MDP account?
												</a></h4>
											</div>
											<div id="collapseThree" class="panel-collapse collapse">
												<div class="panel-body">
													After your MDP account is established, you will receive an account number.  Be sure that any donations in the amount of $5000 or more that you send to PPMD for you MDP account has the MDP account number in the “For” line.
												</div>
											</div>
										</div>
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
												<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
													<i class="icon-arrow"></i>
													4. Does PPMD maintain a separate fiscal account for each of its MDP donors?
												</a></h4>
											</div>
											<div id="collapseFour" class="panel-collapse collapse">
												<div class="panel-body">
													No, we don’t.  Your donation will be credited to your MDP account and tracked there but will be deposited to PPMD’s general funds.  The MDP system allows you to select and designate the research projects in which you are most interested, but these are projects to which the organization has already committed funding so they are part of our general funding budget.  Each project does have an individual budget and when the project has been “fully funded” via MDP allocations, we will close it out and indicate that the project is fully funded.  For example, if a single donor funds a whole project for $100,000 then we would mark that project as “fully funded” and not allow any other donors to allocate funds to it.  As projects become fully funded by MDP donors, PPMD general funds are freed up to invest in new research.
												</div>
											</div>
										</div>
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
												<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
													<i class="icon-arrow"></i>
													5.  What kind of projects are available for MDP allocations?
												</a></h4>
											</div>
											<div id="collapseFive" class="panel-collapse collapse">
												<div class="panel-body">
													We will make available a selection of research projects that have been reviewed by PPMD’s Scientific Advisory Committee or at least two ad hoc scientific advisors, and which have been approved for funding by PPMD’s Board of Directors.  For a research project to be posted on MDP we must have a signed Award Letter in hand from the grantee.  Right now we are offering a series of high profile research projects that will require significant funding to complete.  As time goes on, we hope to gradually transition all of our research projects, including meeting grants, to MDP and we will eventually add projects related to care and advocacy as well.  We firmly believe in the inter-related nature of care, advocacy and therapy development and we want to give you the opportunity to balance your donor portfolio among these categories as you see fit.
												</div>
											</div>
										</div>
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
												<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
													<i class="icon-arrow"></i>
													6.  Can I make an allocation to all the projects in a single therapeutic category?
												</a></h4>
											</div>
											<div id="collapseSix" class="panel-collapse collapse">
												<div class="panel-body">
													Yes.  If you are interested in a specific category of research and would like to fund all the projects in that category you may select the category and then choose “allocate across multiple projects in a single category.”  This action will divide your allocation equally across all the open projects in that category and each individual project will show up on your MDP summary page.
												</div>
											</div>
										</div>
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
												<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven">
													<i class="icon-arrow"></i>
													7.  Can I make multiple allocations from a single deposit to my MDP account?  
												</a></h4>
											</div>
											<div id="collapseSeven" class="panel-collapse collapse">
												<div class="panel-body">
													Yes.  You can allocate to individual projects or to whole categories of projects at once or any combination of the above until all the dollars are allocated.
												</div>
											</div>
										</div>
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
												<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseEight">
													<i class="icon-arrow"></i>
													7.  Do I have to allocate all of an MDP deposit at once?  
												</a></h4>
											</div>
											<div id="collapseEight" class="panel-collapse collapse">
												<div class="panel-body">
													8.  I would really like to contribute some funding to Dr. X’s work.  Can I open an MDP account and then have PPMD fund Dr. X so that I can allocate my funds to him/her?
												</div>
											</div>
										</div>
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
												<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseNine">
													<i class="icon-arrow"></i>
													7.  Do I have to allocate all of an MDP deposit at once?  
												</a></h4>
											</div>
											<div id="collapseNine" class="panel-collapse collapse">
												<div class="panel-body">
													If Dr. X has an approved research grant funded by PPMD that has been reviewed by our scientific advisors and approved by our Board of Directors, then you may allocate your funds to Dr. X by selecting that project from the MDP Active Projects list.  We cannot allow donors to “pass through” funds to a designee of their choice – the IRS does not allow this and we feel strongly that research projects supported by PPMD benefit from rigorous peer review.
												</div>
											</div>
										</div>
									</div>
								</div>
							
							<!-- end: ACCORDION PANEL -->
						</div>
					</div>
<%= render 'layouts/footer' %>

app/views/donor_portfolio/reports.html.erb
<%= render 'layouts/header' %>

<%= render 'layouts/footer' %>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Creative Science Labs</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <link href="/assets/sp-style.css" rel="stylesheet" />
  <link href="/assets/bootstrap_and_overrides.css" rel="stylesheet" />
  <%= javascript_include_tag "application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="container">

<div class="span6 logo">
  <%= link_to image_tag("csl_logo.png") %>
</div>

<div class="span8">
<table class="table table-bordered">
              <thead>
                <tr>
                  <th>Project</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><a href="/fame4good/home">Fame 4 Good</a></td>
                </tr>
                <tr>
                  <td><a href="http://csldev.com/mnm/eoy-ex2.html">Malaria No More - New Year's Resolution</a></td>
                </tr>
                <!--<tr>
                  <td><%= link_to 'Malaria No More - Pinterest',  malaria_path %></td>
                </tr>-->
                <tr>
                  <td><%= link_to 'Symmetry Partners',  symmetry_partners_path %></td>
                </tr>
                <tr>
                  <td><%= link_to 'PPMD',  login_path %></td>
                </tr>
                <tr>
                  <td><a href="http://dev-knight-point.gotpantheon.com/">Knight Point</a></td>
                </tr>
              </tbody>
</table>
</div>
</div>